name: triggers_ejemplos
on: [push]
  braches: ["dev","release/**"]
  paths: ["**.js"]

on: [pull_request]
  types: ["open","labeled"]
  braches: ["dev","release/**"]
  paths: ["**.js"]
  
on: [issues]
  types: ["open","edit"]

on: [issues_comment]
  types: ["open","delete"]

on: [issues_comment]
  jobs: 
    pr_commented:
      name: PR commented
      if: ${{github.event.issue.pull_request}}

on: [workflow_dispatch]
  inputs: 
    alerta:
      description: 'nivel'
      required: true
      defaut: medio
      type: choice
      options: 
      - bajo
      - medio
    tag:
      desciption: 'Optional'
      required: false
      type: boolean
    environment:
      description: 'objetivo'
      type: string
      required: true

on: [scheduler]
  - cron: '30 5 * * *'